version: "3.9"

services:
  app:
    build: .
    container_name: node-app
    restart: unless-stopped
    ports:
      - "3019:3018"
    environment:
      - MONGO_URI=mongodb://mongo:27017/finance
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: finance
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
